### ISSUE TITLE
can this handle UTF-16?

### ISSUE THREAD

**Issue by dbwest** [mislav/gorgeous#1]
I'm getting

```
     c:/Ruby193/lib/ruby/1.9.1/rexml/encoding.rb:41:in `encode': "<?" on UTF-16 (Encoding::InvalidByteSequenceError)
        from c:/Ruby193/lib/ruby/1.9.1/rexml/encoding.rb:41:in `decode'
        from c:/Ruby193/lib/ruby/1.9.1/rexml/source.rb:58:in `encoding='
```

**Comment by mislav** [comment]
I don't know if it can handle UTF-16. Most of the library is tested using UTF-8. The problem of mixed encodings in input is that there's little way to specify the original encoding of the input data. Try this:

``` sh
RUBYOPT="-E utf-8" gorgeous ...
```

where you replace "utf-8" string with the encoding that you're certain that the input data is in.
